Add sync package
Skyrin/go-lib pull request #21
Opened 2021-12-24 00:56 UTC by sagramont

2021-12-28 22:20 UTC, nene209 requested changes
Looks good - some minor changes requested

2021-12-28 22:20 UTC, nene209 commented on sync/db/migrations/000001_sync.up.sql
> +	sync_queue_object_id TEXT NOT NULL, -- This is the object id some services require it, like algolia
Not sure these are needed here (sync_queue_[index/object_id]) - should be part of the app specific implementation?

2021-12-28 22:20 UTC, nene209 commented on sync/db/migrations/000001_sync.up.sql
> +		UNIQUE (sync_queue_index, sync_queue_object_id, sync_queue_service)
If do remove object_id (maybe even if not removing) - this unique should be service+item_type+item_id (in that order I think)

2021-12-28 22:20 UTC, nene209 commented on sync/db/migrations/000001_sync.up.sql
> +	sync_queue_item_hash TEXT NOT NULL,
Maybe add the item (as JSON type)? but leave as nullable - so can leave null for now

2021-12-28 22:20 UTC, nene209 commented on sync/sqlmodel/sync.go
> +}
Would probably put this outside of the sqlmodel package (in the sync package) - AddToQueue or something along those lines (since this isn't code specific to inserting into the db).

2021-12-28 22:20 UTC, nene209 commented on sync/sqlmodel/sync_queue.go
> +func SyncQueueForDeleteUpdate(db *sql.Connection, id int, delete bool) (err error) {
SyncQueueSetDelete?

2021-12-28 22:20 UTC, nene209 commented on sync/sqlmodel/sync_queue.go
> +func SyncQueueForDeleteUpdateByItemID(db *sql.Connection, itemID int, delete bool) (err error) {
This would require the type and service to ensure the correct record was updated. Also same as above? SyncQueueSetDeleteByServiceItemTypeAndItemID

2021-12-28 22:20 UTC, nene209 commented on sync/sqlmodel/sync_queue.go
> +	}
Would not sort by default - let calling function decide whether to sort or not

2021-12-28 22:20 UTC, nene209 commented on sync/sqlmodel/sync_queue.go
> +	}
May want a sort by updated

2021-12-28 22:20 UTC, nene209 commented on sync/sqlmodel/sync_queue.go
> +func SyncQueueGetByItemIDAndService(db *sql.Connection, itemID int,
Probably need to add item type?

2021-12-28 22:20 UTC, nene209 commented on sync/sqlmodel/sync_queue.go
> +func SyncQueueGetItemIDsByService(db *sql.Connection, limit, offset int,
You would need the type as well - or maybe just need the queue id (not sure what this is being used for)?

2021-12-28 22:20 UTC, nene209 commented on sync/sync_provider.go
> +	GetSyncQueueObject(itemID int, syncItemType string) *model.SyncQueue
Maybe just GetJSON function? Not sure it needs the actual object

2021-12-28 22:20 UTC, nene209 commented on sync/sync_provider.go
> +	SyncItem(db *sql.Connection, so *model.SyncQueue) (err error)
SyncItem -> Send?

2021-12-28 22:20 UTC, nene209 commented on sync/sync_provider.go
> +	HandleItemQueue(db *sql.Connection, item *model.SyncQueue) (err error)
What does HandleItemQueue do?

2021-12-28 22:20 UTC, nene209 commented on sync/sync_provider.go
> +func (s *Service) SyncQueueItem(db *sql.Connection, serviceName string,
Sync/Run/Process?

2021-12-28 22:20 UTC, nene209 commented on sync/sync_provider.go
> +// runSync attempts to send all 'pending' and 'failed' records to algolia
delete "to algolia"

2021-12-29 10:39 UTC, sagramont commented on sync/sync_provider.go
> +	HandleItemQueue(db *sql.Connection, item *model.SyncQueue) (err error)
It checks if the item is different and sends the item to the service

2021-12-29 10:47 UTC, sagramont commented on sync/sqlmodel/sync_queue.go
> +	}
Default sort is for the case of using limit and offset, so it's consistent and not required by calling client

2021-12-30 02:16 UTC, nene209 requested changes
Let me know if questions on the logic changes.

2021-12-30 02:16 UTC, nene209 commented on sync/sync_provider.go
> +	HandleItemQueue(db *sql.Connection, item *model.SyncQueue) (err error)
There appears to be duplicate code being created with this logic (after looking at the app specific implementations). I think the provider interface should have two func signatures: Get and Send. Get returns the object (interface{} - probably not used, but maybe) and the json bytes - maybe best to return an interface defined in here that has both of these - with GetJSON and GetObject as func signatures?). The hash can then be calculated in this code based on the JSON bytes. Then, the logic to determine whether to send or not based on hash/deleted can be in a single place in here. Afterwards, if it needs an update, it can call the Send method, which will only send the JSON bytes to the service (saving/updating the hash/status should happen in this package after a successful call). This way the app code only needs to handle fetching the data and sending it to the service.

Also, would probably just name it Provider, since in the sync package.

2021-12-30 02:21 UTC, nene209 commented on sync/model/sync_queue.go
> +	ObjectID  string
Nita Ave

2021-12-30 02:22 UTC, nene209 commented on sync/model/sync_queue.go
> +	ObjectID  string
These should be removed as well - only part of the app specific implementations

2022-01-04 18:38 UTC, sagramont commented on sync/sync_provider.go
> +	HandleItemQueue(db *sql.Connection, item *model.SyncQueue) (err error)
If I understand your feedback correctly, the image data is not processed twice.  The actual image object is not created here though.  GetSyncQueueObject creates a sync_queue table object, without any of the image data.  Then when the sync call comes in, the HandleItemQueue is called, which is where it gets the image data, checks if it exists on the queue table.  If it does exist, checks if it is different, and only sends if different.  If it wasn't on the queue table, it sends to the service.  Whenever the image data is sent to a service, that's when the image data (as a hash right now, although there is a json field as well) is stored on the queue table, for future hash comparisons.  Might be that the function needs a better name to describe its purpose or did I not understand the issue?

2022-01-06 22:38 UTC, merged